get_filename_component(WP_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/.." ABSOLUTE)
find_package(Git REQUIRED)
execute_process(COMMAND "${GIT_EXECUTABLE}" ls-files -- CMakeLists.txt LICENSE THIRD_PARTY_NOTICES.md engine recompiler games/wiiparty third_party tests tools/fetch_sdl.py
                WORKING_DIRECTORY "${WP_ROOT}" OUTPUT_VARIABLE WP_SOURCE_LIST OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND "${GIT_EXECUTABLE}" describe --always --dirty
                WORKING_DIRECTORY "${WP_ROOT}" OUTPUT_VARIABLE WP_SOURCE_REVISION OUTPUT_STRIP_TRAILING_WHITESPACE)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${WP_ROOT}/.git/index")
string(REPLACE "\n" ";" WP_SOURCE_LIST "${WP_SOURCE_LIST}")

set(WP_QRC "<RCC><qresource prefix=\"/source\">\n")
foreach(WP_FILE ${WP_SOURCE_LIST})
    string(APPEND WP_QRC "<file alias=\"${WP_FILE}\">${WP_ROOT}/${WP_FILE}</file>\n")
endforeach()
string(APPEND WP_QRC "</qresource><qresource prefix=\"/licenses\">\n")

get_filename_component(WP_QT_PREFIX "${Qt6_DIR}/../../.." ABSOLUTE)
foreach(WP_CANDIDATE "${WP_QT_PREFIX}/share/licenses" "${WP_QT_PREFIX}/../share/licenses")
    if(NOT WP_LICENSES AND IS_DIRECTORY "${WP_CANDIDATE}/qt6-base")
        get_filename_component(WP_LICENSES "${WP_CANDIDATE}" ABSOLUTE)
    endif()
endforeach()
if(WP_LICENSES)
    foreach(WP_PACKAGE qt6-base brotli bzip2 double-conversion freetype gcc-libs graphite2 harfbuzz libb2 libpng libwinpthread md4c pcre2 zlib zstd)
        file(GLOB WP_PACKAGE_FILES "${WP_LICENSES}/${WP_PACKAGE}/*")
        foreach(WP_FILE ${WP_PACKAGE_FILES})
            get_filename_component(WP_NAME "${WP_FILE}" NAME)
            string(APPEND WP_QRC "<file alias=\"${WP_PACKAGE}/${WP_NAME}\">${WP_FILE}</file>\n")
        endforeach()
    endforeach()
endif()
string(APPEND WP_QRC "</qresource></RCC>\n")

file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/payload.qrc.in" "${WP_QRC}")
configure_file("${CMAKE_CURRENT_BINARY_DIR}/payload.qrc.in" "${CMAKE_CURRENT_BINARY_DIR}/payload.qrc" COPYONLY)
