#pragma once

#include <string>

struct Texts {
    const char* game;
    const char* settings;
    const char* saves;
    const char* controls;
    const char* licenses;
    const char* status_ready;
    const char* status_install;
    const char* play;
    const char* shortcut_options;
    const char* shortcut_fullscreen;
    const char* shortcut_screenshot;
    const char* shortcut_capture;
    const char* update_title;
    const char* update_detail;
    const char* update;
    const char* install_intro;
    const char* install_folder;
    const char* change;
    const char* disc;
    const char* disc_none;
    const char* disc_extracted;
    const char* choose;
    const char* disc_filter;
    const char* install;
    const char* installing;
    const char* cancel;
    const char* try_again;
    const char* back;
    const char* show_details;
    const char* hide_details;
    const char* minutes_left;
    const char* minute_left;
    const char* choose_disc_first;
    const char* space_needed;
    const char* space_short;
    const char* path_too_long;
    const char* tool_ready;
    const char* tool_to_download;
    const char* compile_jobs;
    const char* step_prepare;
    const char* step_tool;
    const char* step_download;
    const char* step_verify;
    const char* step_install;
    const char* step_finish;
    const char* step_extract;
    const char* step_sdl;
    const char* step_unpack;
    const char* step_dol;
    const char* step_modules;
    const char* step_links;
    const char* step_dsp;
    const char* step_configure;
    const char* step_compile;
    const char* build_finished;
    const char* build_failed;
    const char* build_cancelled;
    const char* missing_tool;
    const char* tool_unavailable;
    const char* hash_mismatch;
    const char* extract_failed;
    const char* extracted_files;
    const char* start_failed;
    const char* settings_intro;
    const char* group_video;
    const char* group_input;
    const char* group_system;
    const char* group_audio;
    const char* group_saves;
    const char* saves_intro;
    const char* saves_empty;
    const char* saves_disabled;
    const char* open_folder;
    const char* restore;
    const char* backup_size;
    const char* restore_title;
    const char* restore_question;
    const char* restore_done;
    const char* restore_unchanged;
    const char* restore_failed;
    const char* controls_intro;
    const char* controls_reset;
    const char* keys_clear;
    const char* keys_none;
    const char* keys_press;
    const char* keys_reserved;
    const char* licenses_intro;
    const char* license_project;
    const char* license_notices;
    const char* license_runtime;
};

void use_spanish(bool spanish);
const Texts& texts();
std::string format(const char* pattern, const std::string& first, const std::string& second = {});
const char* option_detail(const std::string& key);
const char* group_name(const std::string& key);
const char* action_name(const char* key);
const char* action_detail(const char* key);
