#include "texts.h"

#include <cstring>

namespace {

constexpr Texts kEnglish = {
    "Game",
    "Settings",
    "Saves",
    "Controls",
    "Licenses",
    "Ready to play.",
    "Choose your copy of Wii Party to install it.",
    "Play",
    "Options",
    "Full screen",
    "Screenshot",
    "Frame capture",
    "An update is ready",
    "This launcher brings a newer version of the game. Install it to rebuild the game; your saves and settings stay as they are.",
    "Update",
    "Installing translates the game from your own disc into a native program. Missing tools are downloaded from their official sites; nothing from the game is downloaded and nothing leaves your computer. It takes about 10 minutes on a 6-core processor.",
    "Install folder",
    "Change",
    "Disc",
    "No disc chosen",
    "Already extracted",
    "Choose",
    "Wii disc images",
    "Install",
    "Installing",
    "Cancel",
    "Try again",
    "Back",
    "Show details",
    "Hide details",
    "About %1 minutes left",
    "About a minute left",
    "Choose your copy of Wii Party first.",
    "Needs about %1 GB of free space. That drive has %2 GB free.",
    "Not enough free space: the installation needs about %1 GB and that drive has %2 GB free.",
    "The install folder path is too long for the compiler. Choose a folder with a shorter path, for example C:\\Games.",
    "%1: %2, ready",
    "%1: missing or not compatible, it will be downloaded",
    "Compiling with %1 parallel jobs.",
    "Prepare the build files",
    "Find %1",
    "Download %1",
    "Check %1",
    "Unpack %1",
    "Finish %1",
    "Extract the disc",
    "Download SDL3 for gamepads",
    "Unpack the code modules",
    "Translate the main executable",
    "Translate the code modules",
    "Link the modules to the main executable",
    "Translate the audio microcode",
    "Configure the build",
    "Compile the game",
    "The game is installed.",
    "The installation stopped at a failed step. The details show the error.",
    "The installation was cancelled.",
    "Missing tool: %1",
    "%1 is missing. Install the build tools with your system's package manager and try again. Debian/Ubuntu: sudo apt install g++ cmake ninja-build python3 curl. Fedora: sudo dnf install gcc-c++ cmake ninja-build python3 curl. Arch: sudo pacman -S --needed gcc cmake ninja python curl.",
    "%1 does not match its published checksum and was deleted. Try again.",
    "Could not write the build files to %1.",
    "Build files written to %1.",
    "The game could not be started.",
    "PC improvements, kept apart from the translated game. They apply the next time the game starts; F10 opens them while playing, where most apply at once.",
    "Video",
    "Input",
    "System",
    "Audio",
    "Saves",
    "Copies of your progress, made automatically. Restoring one replaces the current save, which is first kept as a new copy.",
    "No backups yet. The first one is made the next time the game starts with a save.",
    "Automatic backups are off. Turn them on in Settings.",
    "Open folder",
    "Restore",
    "%1 KB",
    "Restore this backup?",
    "The backup from %1 replaces the current save. Close the game first; the current save is kept as a new backup.",
    "The backup from %1 is now the save.",
    "The save already matches the backup from %1.",
    "The backup could not be restored: %1",
    "Keyboard and mouse for Wii Remote 1. Click a binding, then press a key, click or scroll to add it. F10, F11 and F12 are reserved.",
    "Reset to defaults",
    "Clear",
    "Not set",
    "Press a key, click or scroll",
    "F10, F11 and F12 are reserved",
    "Wii Party Recomp is free software under the GPL-3.0-or-later. The launcher includes the libraries below, each under its own license.",
    "Wii Party Recomp",
    "Third-party notices",
    "GCC runtime",    "Launcher",
    "Check for launcher updates",
    "When it opens, asks GitHub whether a newer launcher exists. Nothing else is sent.",
    "Launcher %1 is available",
    "It is downloaded from GitHub, checked and restarted. Then the game is updated from it.",
    "Update launcher",
    "Downloading…",
    "The launcher could not be updated: %1",
    "About %1 minutes. You can keep playing the current version while it builds.",
    "About %1 minutes, because this update rebuilds the whole game. You can keep playing the current version while it builds.",
    "Play current version",
    "The new version will be used the next time you press Play.",
    "Update the calls between the modules and the executable",
    "Europe (PAL)",
    "Americas (NTSC)",
    "Japan (NTSC)",
    "Korea (NTSC)",
    "Release notes",
    "Repair installation",
    "Translates and compiles the game again from scratch. Saves and settings are kept.",
    "Repair",
    "Repair the installation?",
    "The game is translated and compiled again from the extracted disc. It takes about %1 minutes; you can keep playing the current version meanwhile.",
    "Desktop shortcut",
    "Adds a desktop shortcut that opens this launcher, or the game directly.",
    "Create",
    "Shortcut created on the desktop.",
    "The shortcut could not be created: %1",
    "Textures",
    "Disc versions",
    "Each version keeps its own saves. Switching to a version that is already built is instant.",
    "In use",
    "Use",
    "Will be built when used",
    "Add another version",
    "Choose the disc of another region, such as the NTSC one. Only the parts that differ are built again.",
    "The version could not be changed. Close the game and try again.",
    "Check the disc",
    "Disc checked: %1",
    "The disc is not in the Redump list; the installation continues.",
    "The disc image is damaged or modified. Dump it again from your console.",
    "Switch to the new disc version",
    "This disc version is already installed.",
    "Connected gamepads",
    "No gamepad is connected. Joy-Con, Xbox, PlayStation and other gamepads appear here.",
    "Wii Remote %1",
    "Report a problem",
    "Saves a report with the logs, versions and settings, and opens the issues page on GitHub to attach it.",
    "Create report",
    "Report saved in %1.",
    "What's new in v%1",
    "Close",
    "Screenshots",
    "Opens the folder with the screenshots taken with F9.",
    "Replacement texture packs, with Dolphin's file names. Each pack is a folder in games/wiiparty/textures/load; a pack that is off is kept without being used.",
    "No texture packs yet. Put each pack in its own folder inside the load folder.",
    "%1 files, %2",
    "Custom textures are off in Settings, so no pack is used.",
    "Launcher",
    "Game",
    "Offline mode",
    "The launcher never connects to the internet: no update check and no tool downloads. Missing tools must come from the offline pack next to the launcher or be installed by you.",
    "%1 is missing and offline mode is on. Put the offline tools pack next to the launcher, install %1 yourself, or turn offline mode off in Settings.",
    "%1 %2 (offline pack)",
    "Wii Remotes",
    "Pair a Wii Remote",
    "Open the battery cover, press the red SYNC button and then Pair, while its lights blink. Once paired, any button connects it again. Wii Remotes play as players 1 to 4 in the order they connect.",
    "Pair",
    "Searching...",
    "Wii Remotes paired: %1. Press any button on the remote to use it.",
    "No Wii Remote found. Press the red SYNC button and try again while the lights blink.",
    "Screenshots",
    "System",
    "Test the controls",
    "Player %1",
    "Keyboard and mouse",
    "Press a key or a button to see what the game will receive.",
    "Gamepad buttons",
    "Which gamepad button acts as each Wii Remote button, held upright. Automatic follows the gamepad's layout: A is the bottom button on Xbox pads and the right one on Nintendo pads, and the right shoulder and trigger also act as A and B. Held sideways, the game keeps its own layout.",
    "Automatic",
    "Bottom face button",
    "Right face button",
    "Left face button",
    "Top face button",
    "Back / Select / −",
    "Guide / Home",
    "Start / +",
    "Left stick press",
    "Right stick press",
    "Left shoulder (LB / L)",
    "Right shoulder (RB / R)",
    "D-pad up",
    "D-pad down",
    "D-pad left",
    "D-pad right",
    "Left trigger (LT / ZL)",
    "Right trigger (RT / ZR)",
    "Import from Dolphin",
    "Found in %1: a Wii Party save and Miis (%2). Importing replaces the current save and Miis; the current save is backed up first.",
    "Found in %1: a Wii Party save. Importing replaces the current save, which is backed up first.",
    "Found in %1: Miis (%2), no Wii Party save. Importing replaces the current Miis.",
    "No Dolphin data with a Wii Party save or Miis was found. Choose Dolphin's user folder, the one with the Wii folder inside.",
    "Import",
    "Choose folder",
    "Imported from Dolphin. The previous save is in the list below if you need it back.",
    "The import failed: %1",
    "Save and Miis from Dolphin",
    "Pictures taken with F9 while playing, newest first. Click one to open it.",
    "No screenshots yet. Press F9 while playing to take one.",
    "Showing the newest %1 of %2. Open the folder to see them all.",
    "Information about this PC for problem reports, and tools for the install.",
    "Diagnostics",
    "Copy",
    "Copied to the clipboard.",
    "Launcher",
    "Game",
    "Not installed",
    "System",
    "Processor",
    "%1 threads, %2 GB of RAM",
    "Graphics",
    "Known after the game has been opened once",
    "Display",
    "Gamepads",
    "None",
    "Install folder",
    "%1 (%2 GB free)",
    "Last session",
    "%1 fps on average, lowest %2 fps",
    "No game session yet",
    "Recommended internal resolution: %1",
    "For your %1 display and your graphics card. The current setting is %2.",
    "Your last session dropped below 60 fps, so one step lower is suggested.",
    "Use",
    "In use",
    "Portable mode",
    "Keeps the launcher's settings and the game in the launcher's own folder, to carry it on a USB drive. The launcher restarts to apply it.",
    "Move the game next to the launcher",
    "The game is still in %1. Moving it takes a few minutes when it is on another drive.",
    "Move",
    "Moving... %1%",
    "The game is now next to the launcher.",
    "It did not finish: %1",
    "Uninstall",
    "Deletes the built game, the extracted disc files and the downloaded tools. You choose whether to keep your saves.",
    "Uninstall...",
    "Uninstall Wii Party Recomp from %1?",
    "Keep saves, Miis, settings, screenshots and texture packs",
    "Uninstall",
    "Uninstalling...",
    "Uninstalled. You can also delete the launcher file, or press Install on the Game page to set it up again.",
    "Let the game use Wii Remotes",
    "Linux only lets the administrator open Wii Remotes. This adds a system rule for them and asks for your password once.",
    "Allow",
    "Done. Wii Remotes connected from now on can be used by the game.",
    "The rule was not added.",
};

constexpr Texts kSpanish = {
    "Juego",
    "Opciones",
    "Partidas",
    "Controles",
    "Licencias",
    "Listo para jugar.",
    "Elige tu copia de Wii Party para instalarlo.",
    "Jugar",
    "Opciones",
    "Pantalla completa",
    "Captura",
    "Captura de fotograma",
    "Hay una actualización",
    "Este lanzador trae una versión más nueva del juego. Instálala para recompilarlo; tus partidas y opciones se conservan.",
    "Actualizar",
    "La instalación traduce el juego desde tu propio disco a un programa nativo. Las herramientas que falten se descargan de sus webs oficiales; no se descarga nada del juego y nada sale de tu ordenador. Tarda unos 10 minutos con un procesador de 6 núcleos.",
    "Carpeta de instalación",
    "Cambiar",
    "Disco",
    "Ningún disco elegido",
    "Ya extraído",
    "Elegir",
    "Imágenes de disco de Wii",
    "Instalar",
    "Instalando",
    "Cancelar",
    "Reintentar",
    "Volver",
    "Mostrar detalles",
    "Ocultar detalles",
    "Quedan unos %1 minutos",
    "Queda un minuto",
    "Elige primero tu copia de Wii Party.",
    "Necesita unos %1 GB libres. Esa unidad tiene %2 GB libres.",
    "No hay espacio suficiente: la instalación necesita unos %1 GB y esa unidad tiene %2 GB libres.",
    "La ruta de la carpeta de instalación es demasiado larga para el compilador. Elige una carpeta con una ruta más corta, por ejemplo C:\\Juegos.",
    "%1: %2, lista",
    "%1: falta o no es compatible, se descargará",
    "Compilando con %1 procesos en paralelo.",
    "Preparar los archivos de compilación",
    "Buscar %1",
    "Descargar %1",
    "Comprobar %1",
    "Descomprimir %1",
    "Terminar %1",
    "Extraer el disco",
    "Descargar SDL3 para los mandos",
    "Descomprimir los módulos de código",
    "Traducir el ejecutable principal",
    "Traducir los módulos de código",
    "Enlazar los módulos con el ejecutable",
    "Traducir el microcódigo de audio",
    "Preparar la compilación",
    "Compilar el juego",
    "El juego está instalado.",
    "La instalación se ha detenido en un paso con error. Los detalles muestran el fallo.",
    "La instalación se ha cancelado.",
    "Falta la herramienta: %1",
    "Falta %1. Instala las herramientas de compilación con el gestor de paquetes del sistema y vuelve a intentarlo. Debian/Ubuntu: sudo apt install g++ cmake ninja-build python3 curl. Fedora: sudo dnf install gcc-c++ cmake ninja-build python3 curl. Arch: sudo pacman -S --needed gcc cmake ninja python curl.",
    "%1 no coincide con su suma de comprobación publicada y se ha borrado. Vuelve a intentarlo.",
    "No se han podido escribir los archivos de compilación en %1.",
    "Archivos de compilación escritos en %1.",
    "No se ha podido abrir el juego.",
    "Mejoras de PC, separadas del juego traducido. Se aplican la próxima vez que se abra el juego; F10 las abre durante la partida, donde casi todas se aplican al momento.",
    "Vídeo",
    "Entrada",
    "Sistema",
    "Sonido",
    "Partidas",
    "Copias de tu progreso, hechas automáticamente. Restaurar una sustituye la partida actual, que antes se guarda como una copia nueva.",
    "Aún no hay copias. La primera se hará la próxima vez que el juego se abra con una partida guardada.",
    "Las copias automáticas están desactivadas. Actívalas en Opciones.",
    "Abrir carpeta",
    "Restaurar",
    "%1 KB",
    "¿Restaurar esta copia?",
    "La copia del %1 sustituye a la partida actual. Cierra antes el juego; la partida actual se guarda como una copia nueva.",
    "La copia del %1 es ahora la partida.",
    "La partida ya coincide con la copia del %1.",
    "No se ha podido restaurar la copia: %1",
    "Teclado y ratón para el Wii Remote 1. Pulsa una asignación y después una tecla, un clic o la rueda para añadirla. F10, F11 y F12 están reservadas.",
    "Restablecer",
    "Quitar",
    "Sin asignar",
    "Pulsa una tecla, haz clic o gira la rueda",
    "F10, F11 y F12 están reservadas",
    "Wii Party Recomp es software libre bajo la GPL-3.0-or-later. El lanzador incluye las bibliotecas de abajo, cada una con su propia licencia.",
    "Wii Party Recomp",
    "Avisos de terceros",
    "Runtime de GCC",    "Lanzador",
    "Buscar actualizaciones del lanzador",
    "Al abrirse, pregunta a GitHub si hay un lanzador más nuevo. No se envía nada más.",
    "El lanzador %1 está disponible",
    "Se descarga de GitHub, se comprueba y se reinicia. Después actualiza el juego.",
    "Actualizar lanzador",
    "Descargando…",
    "No se pudo actualizar el lanzador: %1",
    "Unos %1 minutos. Puedes seguir jugando a la versión actual mientras se compila.",
    "Unos %1 minutos, porque esta actualización recompila todo el juego. Puedes seguir jugando a la versión actual mientras se compila.",
    "Jugar a la versión actual",
    "La nueva versión se usará la próxima vez que pulses Jugar.",
    "Actualizar las llamadas entre los módulos y el ejecutable",
    "Europa (PAL)",
    "América (NTSC)",
    "Japón (NTSC)",
    "Corea (NTSC)",
    "Notas de la versión",
    "Reparar instalación",
    "Vuelve a traducir y compilar el juego desde cero. Se conservan las partidas y las opciones.",
    "Reparar",
    "¿Reparar la instalación?",
    "El juego se vuelve a traducir y compilar desde el disco extraído. Tarda unos %1 minutos; mientras tanto puedes seguir jugando a la versión actual.",
    "Acceso directo en el escritorio",
    "Añade en el escritorio un acceso directo que abre este lanzador o directamente el juego.",
    "Crear",
    "Acceso directo creado en el escritorio.",
    "No se pudo crear el acceso directo: %1",
    "Texturas",
    "Versiones del disco",
    "Cada versión tiene sus propias partidas. Cambiar a una versión ya compilada es instantáneo.",
    "En uso",
    "Usar",
    "Se compilará al usarla",
    "Añadir otra versión",
    "Elige el disco de otra región, como el NTSC. Solo se vuelve a compilar lo que cambia.",
    "No se pudo cambiar de versión. Cierra el juego y vuelve a intentarlo.",
    "Comprobar el disco",
    "Disco comprobado: %1",
    "El disco no está en la lista de Redump; la instalación continúa.",
    "La imagen del disco está dañada o modificada. Vuelve a volcarla desde tu consola.",
    "Cambiar a la nueva versión del disco",
    "Esta versión del disco ya está instalada.",
    "Mandos conectados",
    "No hay ningún mando conectado. Aquí aparecen los Joy-Con y los mandos de Xbox, PlayStation y otros.",
    "Wii Remote %1",
    "Informar de un problema",
    "Guarda un informe con los registros, las versiones y las opciones, y abre la página de problemas de GitHub para adjuntarlo.",
    "Crear informe",
    "Informe guardado en %1.",
    "Novedades de la v%1",
    "Cerrar",
    "Capturas de pantalla",
    "Abre la carpeta con las capturas hechas con F9.",
    "Packs de texturas de reemplazo, con los nombres de archivo de Dolphin. Cada pack es una carpeta en games/wiiparty/textures/load; un pack desactivado se conserva sin usarse.",
    "Aún no hay packs de texturas. Pon cada pack en su propia carpeta dentro de la carpeta load.",
    "%1 archivos, %2",
    "Las texturas personalizadas están desactivadas en Opciones, así que no se usa ningún pack.",
    "Lanzador",
    "Juego",
    "Modo sin conexión",
    "El lanzador no se conecta nunca a Internet: no busca actualizaciones ni descarga herramientas. Las que falten deben venir del paquete sin conexión junto al lanzador o instalarlas tú.",
    "Falta %1 y el modo sin conexión está activado. Pon el paquete de herramientas sin conexión junto al lanzador, instala %1 tú mismo o desactiva el modo sin conexión en Ajustes.",
    "%1 %2 (paquete sin conexión)",
    "Wii Remotes",
    "Emparejar un Wii Remote",
    "Abre la tapa de las pilas, pulsa el botón rojo SYNC y después Emparejar, mientras parpadean las luces. Una vez emparejado, cualquier botón lo vuelve a conectar. Los Wii Remote juegan como jugadores 1 a 4 en el orden en que se conectan.",
    "Emparejar",
    "Buscando...",
    "Wii Remotes emparejados: %1. Pulsa cualquier botón del mando para usarlo.",
    "No se ha encontrado ningún Wii Remote. Pulsa el botón rojo SYNC y vuelve a intentarlo mientras parpadean las luces.",
    "Capturas",
    "Sistema",
    "Probar los controles",
    "Jugador %1",
    "Teclado y ratón",
    "Pulsa una tecla o un botón para ver lo que recibirá el juego.",
    "Botones del mando",
    "Qué botón del mando hace de cada botón del Wii Remote, en vertical. Automático sigue la distribución del mando: A es el botón de abajo en los mandos de Xbox y el de la derecha en los de Nintendo, y el gatillo y el botón superior derechos también hacen de A y B. En horizontal, el juego usa su propia distribución.",
    "Automático",
    "Botón de abajo",
    "Botón de la derecha",
    "Botón de la izquierda",
    "Botón de arriba",
    "Back / Select / −",
    "Guía / Home",
    "Start / +",
    "Pulsar el stick izquierdo",
    "Pulsar el stick derecho",
    "Botón superior izquierdo (LB / L)",
    "Botón superior derecho (RB / R)",
    "Cruceta arriba",
    "Cruceta abajo",
    "Cruceta izquierda",
    "Cruceta derecha",
    "Gatillo izquierdo (LT / ZL)",
    "Gatillo derecho (RT / ZR)",
    "Importar desde Dolphin",
    "Encontrado en %1: una partida de Wii Party y Miis (%2). Importar sustituye la partida y los Miis actuales; antes se hace una copia de la partida actual.",
    "Encontrado en %1: una partida de Wii Party. Importar sustituye la partida actual, de la que antes se hace una copia.",
    "Encontrado en %1: Miis (%2), sin partida de Wii Party. Importar sustituye los Miis actuales.",
    "No se han encontrado datos de Dolphin con una partida de Wii Party o Miis. Elige la carpeta de usuario de Dolphin, la que tiene dentro la carpeta Wii.",
    "Importar",
    "Elegir carpeta",
    "Importado desde Dolphin. La partida anterior está en la lista de abajo por si la necesitas.",
    "La importación ha fallado: %1",
    "Partida y Miis de Dolphin",
    "Imágenes hechas con F9 mientras juegas, de la más nueva a la más antigua. Haz clic en una para abrirla.",
    "Aún no hay capturas. Pulsa F9 mientras juegas para hacer una.",
    "Se muestran las %1 más nuevas de %2. Abre la carpeta para verlas todas.",
    "Información de este PC para los informes de problemas, y herramientas de la instalación.",
    "Diagnóstico",
    "Copiar",
    "Copiado al portapapeles.",
    "Lanzador",
    "Juego",
    "No instalado",
    "Sistema",
    "Procesador",
    "%1 hilos, %2 GB de RAM",
    "Gráficos",
    "Se sabrá después de abrir el juego una vez",
    "Pantalla",
    "Mandos",
    "Ninguno",
    "Carpeta de instalación",
    "%1 (%2 GB libres)",
    "Última sesión",
    "%1 fps de media, mínimo %2 fps",
    "Aún no se ha jugado",
    "Resolución interna recomendada: %1",
    "Para tu pantalla de %1 y tu tarjeta gráfica. El ajuste actual es %2.",
    "Tu última sesión bajó de 60 fps, así que se sugiere un paso menos.",
    "Usar",
    "En uso",
    "Modo portable",
    "Guarda los ajustes del lanzador y el juego en la propia carpeta del lanzador, para llevarlo en un USB. El lanzador se reinicia para aplicarlo.",
    "Mover el juego junto al lanzador",
    "El juego sigue en %1. Moverlo tarda unos minutos si está en otra unidad.",
    "Mover",
    "Moviendo... %1 %",
    "El juego ya está junto al lanzador.",
    "No ha terminado: %1",
    "Desinstalar",
    "Borra el juego compilado, los archivos extraídos del disco y las herramientas descargadas. Tú eliges si conservar tus partidas.",
    "Desinstalar...",
    "¿Desinstalar Wii Party Recomp de %1?",
    "Conservar partidas, Miis, ajustes, capturas y packs de texturas",
    "Desinstalar",
    "Desinstalando...",
    "Desinstalado. También puedes borrar el archivo del lanzador, o pulsar Instalar en la página Juego para volver a instalarlo.",
    "Dejar que el juego use los Wii Remote",
    "Linux solo deja abrir los Wii Remote al administrador. Esto añade una regla del sistema para ellos y pide tu contraseña una vez.",
    "Permitir",
    "Hecho. El juego podrá usar los Wii Remote que se conecten a partir de ahora.",
    "No se ha añadido la regla.",
};

constexpr Texts kGalician = {
    "Xogo",
    "Opcións",
    "Partidas",
    "Controis",
    "Licenzas",
    "Listo para xogar.",
    "Escolle a túa copia de Wii Party para instalalo.",
    "Xogar",
    "Opcións",
    "Pantalla completa",
    "Captura",
    "Captura de fotograma",
    "Hai unha actualización",
    "Este lanzador trae unha versión máis nova do xogo. Instálaa para recompilalo; as túas partidas e opcións consérvanse.",
    "Actualizar",
    "A instalación traduce o xogo desde o teu propio disco a un programa nativo. As ferramentas que falten descárganse das súas webs oficiais; non se descarga nada do xogo e nada sae do teu ordenador. Tarda uns 10 minutos cun procesador de 6 núcleos.",
    "Cartafol de instalación",
    "Cambiar",
    "Disco",
    "Ningún disco escollido",
    "Xa extraído",
    "Escoller",
    "Imaxes de disco de Wii",
    "Instalar",
    "Instalando",
    "Cancelar",
    "Tentar de novo",
    "Volver",
    "Amosar detalles",
    "Agochar detalles",
    "Quedan uns %1 minutos",
    "Queda un minuto",
    "Escolle primeiro a túa copia de Wii Party.",
    "Precisa uns %1 GB libres. Esa unidade ten %2 GB libres.",
    "Non hai espazo abondo: a instalación precisa uns %1 GB e esa unidade ten %2 GB libres.",
    "A ruta do cartafol de instalación é demasiado longa para o compilador. Escolle un cartafol cunha ruta máis curta, por exemplo C:\\Xogos.",
    "%1: %2, lista",
    "%1: falta ou non é compatible, descargarase",
    "Compilando con %1 procesos en paralelo.",
    "Preparar os ficheiros de compilación",
    "Buscar %1",
    "Descargar %1",
    "Comprobar %1",
    "Descomprimir %1",
    "Rematar %1",
    "Extraer o disco",
    "Descargar SDL3 para os mandos",
    "Descomprimir os módulos de código",
    "Traducir o executable principal",
    "Traducir os módulos de código",
    "Ligar os módulos co executable",
    "Traducir o microcódigo de audio",
    "Preparar a compilación",
    "Compilar o xogo",
    "O xogo está instalado.",
    "A instalación detívose nun paso con erro. Os detalles amosan o fallo.",
    "A instalación cancelouse.",
    "Falta a ferramenta: %1",
    "Falta %1. Instala as ferramentas de compilación co xestor de paquetes do sistema e téntao de novo. Debian/Ubuntu: sudo apt install g++ cmake ninja-build python3 curl. Fedora: sudo dnf install gcc-c++ cmake ninja-build python3 curl. Arch: sudo pacman -S --needed gcc cmake ninja python curl.",
    "%1 non coincide coa súa suma de comprobación publicada e borrouse. Téntao de novo.",
    "Non se puideron escribir os ficheiros de compilación en %1.",
    "Ficheiros de compilación escritos en %1.",
    "Non se puido abrir o xogo.",
    "Melloras de PC, separadas do xogo traducido. Aplícanse a próxima vez que se abra o xogo; F10 ábreas durante a partida, onde case todas se aplican ao momento.",
    "Vídeo",
    "Entrada",
    "Sistema",
    "Son",
    "Partidas",
    "Copias do teu progreso, feitas automaticamente. Restaurar unha substitúe a partida actual, que antes se garda como unha copia nova.",
    "Aínda non hai copias. A primeira farase a próxima vez que o xogo se abra cunha partida gardada.",
    "As copias automáticas están desactivadas. Actívaas en Opcións.",
    "Abrir cartafol",
    "Restaurar",
    "%1 KB",
    "Restaurar esta copia?",
    "A copia do %1 substitúe a partida actual. Pecha antes o xogo; a partida actual gárdase como unha copia nova.",
    "A copia do %1 é agora a partida.",
    "A partida xa coincide coa copia do %1.",
    "Non se puido restaurar a copia: %1",
    "Teclado e rato para o Wii Remote 1. Preme unha asignación e despois unha tecla, un clic ou a roda para engadila. F10, F11 e F12 están reservadas.",
    "Restablecer",
    "Quitar",
    "Sen asignar",
    "Preme unha tecla, fai clic ou xira a roda",
    "F10, F11 e F12 están reservadas",
    "Wii Party Recomp é software libre baixo a GPL-3.0-or-later. O lanzador inclúe as bibliotecas de embaixo, cada unha coa súa propia licenza.",
    "Wii Party Recomp",
    "Avisos de terceiros",
    "Runtime de GCC",
    "Lanzador",
    "Buscar actualizacións do lanzador",
    "Ao abrirse, pregúntalle a GitHub se hai un lanzador máis novo. Non se envía nada máis.",
    "O lanzador %1 está dispoñible",
    "Descárgase de GitHub, compróbase e reiníciase. Despois actualiza o xogo.",
    "Actualizar lanzador",
    "Descargando…",
    "Non se puido actualizar o lanzador: %1",
    "Uns %1 minutos. Podes seguir xogando á versión actual mentres se compila.",
    "Uns %1 minutos, porque esta actualización recompila todo o xogo. Podes seguir xogando á versión actual mentres se compila.",
    "Xogar á versión actual",
    "A nova versión usarase a próxima vez que premas Xogar.",
    "Actualizar as chamadas entre os módulos e o executable",
    "Europa (PAL)",
    "América (NTSC)",
    "Xapón (NTSC)",
    "Corea (NTSC)",
    "Notas da versión",
    "Reparar instalación",
    "Volve traducir e compilar o xogo desde cero. Consérvanse as partidas e as opcións.",
    "Reparar",
    "Reparar a instalación?",
    "O xogo vólvese traducir e compilar desde o disco extraído. Tarda uns %1 minutos; mentres tanto podes seguir xogando á versión actual.",
    "Acceso directo no escritorio",
    "Engade no escritorio un acceso directo que abre este lanzador ou directamente o xogo.",
    "Crear",
    "Acceso directo creado no escritorio.",
    "Non se puido crear o acceso directo: %1",
    "Texturas",
    "Versións do disco",
    "Cada versión ten as súas propias partidas. Cambiar a unha versión xa compilada é instantáneo.",
    "En uso",
    "Usar",
    "Compilarase ao usala",
    "Engadir outra versión",
    "Escolle o disco doutra rexión, como o NTSC. Só se volve compilar o que cambia.",
    "Non se puido cambiar de versión. Pecha o xogo e téntao de novo.",
    "Comprobar o disco",
    "Disco comprobado: %1",
    "O disco non está na lista de Redump; a instalación continúa.",
    "A imaxe do disco está danada ou modificada. Vólvea envorcar desde a túa consola.",
    "Cambiar á nova versión do disco",
    "Esta versión do disco xa está instalada.",
    "Mandos conectados",
    "Non hai ningún mando conectado. Aquí aparecen os Joy-Con e os mandos de Xbox, PlayStation e outros.",
    "Wii Remote %1",
    "Informar dun problema",
    "Garda un informe cos rexistros, as versións e as opcións, e abre a páxina de problemas de GitHub para anexalo.",
    "Crear informe",
    "Informe gardado en %1.",
    "Novidades da v%1",
    "Pechar",
    "Capturas de pantalla",
    "Abre o cartafol coas capturas feitas con F9.",
    "Packs de texturas de substitución, cos nomes de ficheiro de Dolphin. Cada pack é un cartafol en games/wiiparty/textures/load; un pack desactivado consérvase sen usarse.",
    "Aínda non hai packs de texturas. Pon cada pack no seu propio cartafol dentro do cartafol load.",
    "%1 ficheiros, %2",
    "As texturas personalizadas están desactivadas en Opcións, así que non se usa ningún pack.",
    "Lanzador",
    "Xogo",
    "Modo sen conexión",
    "O lanzador non se conecta nunca a Internet: non busca actualizacións nin descarga ferramentas. As que falten deben vir do paquete sen conexión xunto ao lanzador ou instalalas ti.",
    "Falta %1 e o modo sen conexión está activado. Pon o paquete de ferramentas sen conexión xunto ao lanzador, instala %1 ti mesmo ou desactiva o modo sen conexión en Opcións.",
    "%1 %2 (paquete sen conexión)",
    "Wii Remotes",
    "Emparellar un Wii Remote",
    "Abre a tapa das pilas, preme o botón vermello SYNC e despois Emparellar, mentres pestanexan as luces. Unha vez emparellado, calquera botón volve conectalo. Os Wii Remote xogan como xogadores 1 a 4 na orde en que se conectan.",
    "Emparellar",
    "Buscando...",
    "Wii Remotes emparellados: %1. Preme calquera botón do mando para usalo.",
    "Non se atopou ningún Wii Remote. Preme o botón vermello SYNC e téntao de novo mentres pestanexan as luces.",
    "Capturas",
    "Sistema",
    "Probar os controis",
    "Xogador %1",
    "Teclado e rato",
    "Preme unha tecla ou un botón para ver o que recibirá o xogo.",
    "Botóns do mando",
    "Que botón do mando fai de cada botón do Wii Remote, en vertical. Automático segue a distribución do mando: A é o botón de abaixo nos mandos de Xbox e o da dereita nos de Nintendo, e o gatillo e o botón superior dereitos tamén fan de A e B. En horizontal, o xogo usa a súa propia distribución.",
    "Automático",
    "Botón de abaixo",
    "Botón da dereita",
    "Botón da esquerda",
    "Botón de arriba",
    "Back / Select / −",
    "Guía / Home",
    "Start / +",
    "Premer o stick esquerdo",
    "Premer o stick dereito",
    "Botón superior esquerdo (LB / L)",
    "Botón superior dereito (RB / R)",
    "Cruceta arriba",
    "Cruceta abaixo",
    "Cruceta esquerda",
    "Cruceta dereita",
    "Gatillo esquerdo (LT / ZL)",
    "Gatillo dereito (RT / ZR)",
    "Importar desde Dolphin",
    "Atopado en %1: unha partida de Wii Party e Miis (%2). Importar substitúe a partida e os Miis actuais; antes faise unha copia da partida actual.",
    "Atopado en %1: unha partida de Wii Party. Importar substitúe a partida actual, da que antes se fai unha copia.",
    "Atopado en %1: Miis (%2), sen partida de Wii Party. Importar substitúe os Miis actuais.",
    "Non se atoparon datos de Dolphin cunha partida de Wii Party ou Miis. Escolle o cartafol de usuario de Dolphin, o que ten dentro o cartafol Wii.",
    "Importar",
    "Escoller cartafol",
    "Importado desde Dolphin. A partida anterior está na lista de embaixo por se a precisas.",
    "A importación fallou: %1",
    "Partida e Miis de Dolphin",
    "Imaxes feitas con F9 mentres xogas, da máis nova á máis antiga. Fai clic nunha para abrila.",
    "Aínda non hai capturas. Preme F9 mentres xogas para facer unha.",
    "Amósanse as %1 máis novas de %2. Abre o cartafol para velas todas.",
    "Información deste PC para os informes de problemas, e ferramentas da instalación.",
    "Diagnóstico",
    "Copiar",
    "Copiado no portapapeis.",
    "Lanzador",
    "Xogo",
    "Non instalado",
    "Sistema",
    "Procesador",
    "%1 fíos, %2 GB de RAM",
    "Gráficos",
    "Saberase despois de abrir o xogo unha vez",
    "Pantalla",
    "Mandos",
    "Ningún",
    "Cartafol de instalación",
    "%1 (%2 GB libres)",
    "Última sesión",
    "%1 fps de media, mínimo %2 fps",
    "Aínda non se xogou",
    "Resolución interna recomendada: %1",
    "Para a túa pantalla de %1 e a túa tarxeta gráfica. O axuste actual é %2.",
    "A túa última sesión baixou de 60 fps, así que se suxire un paso menos.",
    "Usar",
    "En uso",
    "Modo portátil",
    "Garda os axustes do lanzador e o xogo no propio cartafol do lanzador, para levalo nun USB. O lanzador reiníciase para aplicalo.",
    "Mover o xogo xunto ao lanzador",
    "O xogo segue en %1. Movelo tarda uns minutos se está noutra unidade.",
    "Mover",
    "Movendo... %1 %",
    "O xogo xa está xunto ao lanzador.",
    "Non rematou: %1",
    "Desinstalar",
    "Borra o xogo compilado, os ficheiros extraídos do disco e as ferramentas descargadas. Ti escolles se conservar as túas partidas.",
    "Desinstalar...",
    "Desinstalar Wii Party Recomp de %1?",
    "Conservar partidas, Miis, axustes, capturas e packs de texturas",
    "Desinstalar",
    "Desinstalando...",
    "Desinstalado. Tamén podes borrar o ficheiro do lanzador, ou premer Instalar na páxina Xogo para volver instalalo.",
    "Deixar que o xogo use os Wii Remote",
    "Linux só deixa abrir os Wii Remote ao administrador. Isto engade unha regra do sistema para eles e pide o teu contrasinal unha vez.",
    "Permitir",
    "Feito. O xogo poderá usar os Wii Remote que se conecten a partir de agora.",
    "Non se engadiu a regra.",
};

struct Detail {
    const char* key;
    const char* english;
    const char* spanish;
    const char* galician;
};

constexpr Detail kDetails[] = {
    {"video.scale", "Renders the game at a multiple of the console's resolution.",
     "Dibuja el juego a un múltiplo de la resolución de la consola.",
     "Debuxa o xogo a un múltiplo da resolución da consola."},
    {"video.fullscreen", "Starts in borderless full screen. F11 also switches it while playing.",
     "Empieza en pantalla completa sin bordes. F11 también la cambia durante la partida.",
     "Comeza en pantalla completa sen bordos. F11 tamén a cambia durante a partida."},
    {"video.copy_filter", "The soft vertical filter the game uses on the console. Turn it off for a sharper picture.",
     "El suave filtro vertical que usa el juego en la consola. Desactívalo para una imagen más nítida.",
     "O suave filtro vertical que usa o xogo na consola. Desactívao para unha imaxe máis nítida."},
    {"video.custom_textures", "Uses the replacement textures in games/wiiparty/textures/load, with Dolphin's file names.",
     "Usa las texturas de reemplazo de games/wiiparty/textures/load, con los nombres de archivo de Dolphin.",
     "Usa as texturas de substitución de games/wiiparty/textures/load, cos nomes de ficheiro de Dolphin."},
    {"video.dump_textures", "Saves each texture the game uses to games/wiiparty/textures/dump, for making texture packs.",
     "Guarda cada textura que usa el juego en games/wiiparty/textures/dump, para crear packs de texturas.",
     "Garda cada textura que usa o xogo en games/wiiparty/textures/dump, para crear packs de texturas."},
    {"input.gamepads", "Up to four gamepads act as Wii Remotes 1 to 4.",
     "Hasta cuatro mandos funcionan como los Wii Remote 1 a 4.",
     "Ata catro mandos funcionan como os Wii Remote 1 a 4."},
    {"input.auto_grip", "Holds the emulated Wii Remote sideways in the minigames that ask for it.",
     "Sujeta el Wii Remote emulado en horizontal en los minijuegos que lo piden.",
     "Suxeita o Wii Remote emulado en horizontal nos minixogos que o piden."},
    {"input.joycon_pairs", "A left and a right Joy-Con act as one Wii Remote. Off, each Joy-Con is its own Wii Remote, held sideways. Applies the next time the game opens.",
     "Un Joy-Con izquierdo y uno derecho funcionan como un solo Wii Remote. Desactivado, cada Joy-Con es un Wii Remote, en horizontal. Se aplica al abrir el juego.",
     "Un Joy-Con esquerdo e un dereito funcionan como un só Wii Remote. Desactivado, cada Joy-Con é un Wii Remote, en horizontal. Aplícase ao abrir o xogo."},
    {"input.real_wiimotes", "Wii Remotes paired with this PC over Bluetooth play as players 1 to 4, in the order they connect, instead of the keyboard or gamepad of that player. Applies the next time the game opens.",
     "Los Wii Remote emparejados con este PC por Bluetooth juegan como jugadores 1 a 4, en el orden en que se conectan, en lugar del teclado o el mando de ese jugador. Se aplica al abrir el juego.",
     "Os Wii Remote emparellados con este PC por Bluetooth xogan como xogadores 1 a 4, na orde en que se conectan, no canto do teclado ou do mando dese xogador. Aplícase ao abrir o xogo."},
    {"input.real_wiimote_mouse", "When the real Wii Remote of player 1 sees no sensor bar, the mouse moves its pointer. Its buttons and motion still come from the remote.",
     "Cuando el Wii Remote real del jugador 1 no ve ninguna barra de sensores, el ratón mueve su puntero. Los botones y el movimiento siguen saliendo del mando.",
     "Cando o Wii Remote real do xogador 1 non ve ningunha barra de sensores, o rato move o seu punteiro. Os botóns e o movemento seguen saíndo do mando."},
    {"input.wake_on_mouse", "Moving the mouse reconnects a Wii Remote the game disconnected for inactivity.",
     "Mover el ratón reconecta un Wii Remote que el juego desconectó por inactividad.",
     "Mover o rato reconecta un Wii Remote que o xogo desconectou por inactividade."},
    {"input.hide_cursor", "Hides the system cursor over the game; the game draws its own pointer.",
     "Oculta el cursor del sistema sobre el juego; el juego dibuja su propio puntero.",
     "Agocha o cursor do sistema sobre o xogo; o xogo debuxa o seu propio punteiro."},
    {"system.interface_language", "The language of this launcher and of the F10 menu.",
     "El idioma de este lanzador y del menú F10.",
     "O idioma deste lanzador e do menú F10."},
    {"system.language", "The language of the virtual console, which the game follows.",
     "El idioma de la consola virtual, que el juego sigue.",
     "O idioma da consola virtual, que o xogo segue."},
    {"system.pal60", "The console's own PAL60 setting. Off runs the game at 50 Hz.",
     "El ajuste PAL60 de la propia consola. Desactivado, el juego va a 50 Hz.",
     "O axuste PAL60 da propia consola. Desactivado, o xogo vai a 50 Hz."},
    {"system.skip_notices", "Presses A on the Wii Remote strap notice at start, as a player would.",
     "Pulsa A en el aviso de la correa del Wii Remote al empezar, como haría un jugador.",
     "Preme A no aviso da correa do Wii Remote ao comezar, como faría un xogador."},
    {"system.options_menu", "F10, or Start with Guide or Back on a gamepad, opens these settings over the game.",
     "F10, o Start con Guide o Back en un mando, abre estas opciones sobre el juego.",
     "F10, ou Start con Guide ou Back nun mando, abre estas opcións sobre o xogo."},
    {"audio.mute", "Silences the game's sound.",
     "Quita el sonido del juego.",
     "Quita o son do xogo."},
    {"saves.backups", "Copies of the save to keep. One is made at every start when the save changed, and at most once a minute after the game saves.",
     "Copias de la partida que se guardan. Se hace una al abrir el juego si la partida ha cambiado, y como mucho una por minuto después de que el juego guarde.",
     "Copias da partida que se gardan. Faise unha ao abrir o xogo se a partida cambiou, e como moito unha por minuto despois de que o xogo garde."},
};

struct Action {
    const char* key;
    const char* english;
    const char* spanish;
    const char* english_detail;
    const char* spanish_detail;
    const char* galician;
    const char* galician_detail;
};

constexpr Action kActions[] = {
    {"a", "A button", "Botón A", nullptr, nullptr, "Botón A", nullptr},
    {"b", "B button", "Botón B", nullptr, nullptr, "Botón B", nullptr},
    {"one", "1 button", "Botón 1", nullptr, nullptr, "Botón 1", nullptr},
    {"two", "2 button", "Botón 2", nullptr, nullptr, "Botón 2", nullptr},
    {"plus", "+ button", "Botón +", nullptr, nullptr, "Botón +", nullptr},
    {"minus", "- button", "Botón -", nullptr, nullptr, "Botón -", nullptr},
    {"home", "HOME button", "Botón HOME", nullptr, nullptr, "Botón HOME", nullptr},
    {"up", "D-pad up", "Cruceta arriba", "Left on screen when the remote is held sideways.", "Izquierda en pantalla con el mando en horizontal.", "Cruceta arriba", "Esquerda na pantalla co mando en horizontal."},
    {"down", "D-pad down", "Cruceta abajo", "Right on screen when the remote is held sideways.", "Derecha en pantalla con el mando en horizontal.", "Cruceta abaixo", "Dereita na pantalla co mando en horizontal."},
    {"left", "D-pad left", "Cruceta izquierda", "Down on screen when the remote is held sideways.", "Abajo en pantalla con el mando en horizontal.", "Cruceta esquerda", "Abaixo na pantalla co mando en horizontal."},
    {"right", "D-pad right", "Cruceta derecha", "Up on screen when the remote is held sideways.", "Arriba en pantalla con el mando en horizontal.", "Cruceta dereita", "Arriba na pantalla co mando en horizontal."},
    {"shake", "Shake", "Agitar", nullptr, nullptr, "Axitar", nullptr},
    {"swing_up", "Swing up", "Mover hacia arriba", "The mouse wheel gives a short swing.", "La rueda del ratón da un movimiento corto.", "Mover cara arriba", "A roda do rato dá un movemento curto."},
    {"swing_down", "Swing down", "Mover hacia abajo", "The mouse wheel gives a short swing.", "La rueda del ratón da un movimiento corto.", "Mover cara abaixo", "A roda do rato dá un movemento curto."},
    {"tilt_left", "Tilt left", "Inclinar a la izquierda", nullptr, nullptr, "Inclinar á esquerda", nullptr},
    {"tilt_right", "Tilt right", "Inclinar a la derecha", nullptr, nullptr, "Inclinar á dereita", nullptr},
    {"tilt_up", "Tilt up", "Inclinar hacia arriba", nullptr, nullptr, "Inclinar cara arriba", nullptr},
    {"tilt_down", "Tilt down", "Inclinar hacia abajo", nullptr, nullptr, "Inclinar cara abaixo", nullptr},
    {"grip", "Swap upright and sideways grip", "Cambiar entre agarre vertical y horizontal", nullptr, nullptr, "Cambiar entre agarre vertical e horizontal", nullptr},
    {"screenshot", "Screenshot", "Captura de pantalla", "Saves the picture of the game as PNG in the screenshots folder.", "Guarda la imagen del juego como PNG en la carpeta screenshots.", "Captura de pantalla", "Garda a imaxe do xogo como PNG no cartafol screenshots."},
};

int g_language = 0;

const Action* find_action(const char* key) {
    for (const Action& action : kActions) {
        if (std::strcmp(action.key, key) == 0) {
            return &action;
        }
    }
    return nullptr;
}

}

void use_language(const std::string& code) {
    g_language = code == "es" ? 1 : code == "gl" ? 2 : 0;
}

bool language_is(const char* code) {
    const char* codes[] = {"en", "es", "gl"};
    return std::strcmp(codes[g_language], code) == 0;
}

const Texts& texts() {
    const Texts* tables[] = {&kEnglish, &kSpanish, &kGalician};
    return *tables[g_language];
}

std::string format(const char* pattern, const std::string& first, const std::string& second) {
    std::string result;
    for (const char* c = pattern; *c; c++) {
        if (c[0] == '%' && (c[1] == '1' || c[1] == '2')) {
            result += c[1] == '1' ? first : second;
            c++;
        } else {
            result += *c;
        }
    }
    return result;
}

const char* option_detail(const std::string& key) {
    for (const Detail& detail : kDetails) {
        if (key == detail.key) {
            const char* choices[] = {detail.english, detail.spanish, detail.galician};
            return choices[g_language];
        }
    }
    return "";
}

const char* group_name(const std::string& key) {
    const Texts& t = texts();
    std::string group = key.substr(0, key.find('.'));
    if (group == "video") {
        return t.group_video;
    }
    if (group == "input") {
        return t.group_input;
    }
    if (group == "audio") {
        return t.group_audio;
    }
    if (group == "saves") {
        return t.group_saves;
    }
    return t.group_system;
}

const char* action_name(const char* key) {
    const Action* action = find_action(key);
    if (!action) {
        return key;
    }
    const char* choices[] = {action->english, action->spanish, action->galician};
    return choices[g_language];
}

const char* action_detail(const char* key) {
    const Action* action = find_action(key);
    if (!action || !action->english_detail) {
        return nullptr;
    }
    const char* choices[] = {action->english_detail, action->spanish_detail, action->galician_detail};
    return choices[g_language];
}
